title: My JSON Skill Manifests
description: A collection of skill manifest files
markdown: kramdown
theme: jekyll-theme-Modernist
plugins:
  - jekyll-seo-tag

# Optional: if you want to include custom directories
include:
  - _layouts
  - assets

# Optional: if you want to exclude certain files or folders
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
